export default [`Alaska REACH Academy`,
`Dot Lake School`,
`Eagle Community School`,
`Mentasta Lake School`,
`Tanacross School`,
`Tetlin School`,
`Tok School`,
`Walter Northway School`,
`Adak School`,
`Yakov E. Netsvetov School`,
`Akutan School`,
`King Cove School`,
`Sand Point School`,
`False Pass School`,
`Charles R. Leask Sr. Middle School`,
`Metlakatla High School`,
`Richard Johnson Elementary`,
`Aniguiin School`,
`Anthony A. Andrews School`,
`Brevig Mission School`,
`Diomede School`,
`Gambell School`,
`Hogarth Kingeekuk Sr. Memorial School`,
`James C. Isabell School`,
`Koyuk-Malimiut School`,
`Martin L. Olson School`,
`Shaktoolik School`,
`Shishmaref School`,
`Tukurngailnguq School`,
`Unalakleet School`,
`Wales School`,
`White Mountain School`,
`Bristol Bay Correspondence`,
`Bristol Bay Middle/High School`,
`Naknek Elementary`,
`Angoon School`,
`Chatham Correspondence`,
`Gustavus School`,
`Klukwan School`,
`Chenega Bay School`,
`FOCUS Homeschool`,
`Tatitlek Community School`,
`Whittier Community School`,
`Glennallen Elementary`,
`Glennallen Jr/Sr High School`,
`Kenny Lake School`,
`Slana School`,
`Upstream Learning Correspondence`,
`Cordova Jr/Sr High School`,
`Mt. Eccles Elementary`,
`Craig Elementary`,
`Craig High School`,
`Craig Middle School`,
`PACE Correspondence`,
`Delta Junction Elementary`,
`Delta Junction Junior High School`,
`Delta Junction Senior High School`,
`Delta/Greely Homeschool`,
`Gerstle River School`,
`Anderson School`,
`Cantwell School`,
`Denali PEAK`,
`Tri-Valley School`,
`Dillingham Elementary`,
`Dillingham Middle/High School`,
`Dillingham Correspondence School`,
`Alternative Learning Systems`,
`Anne Wien Elementary`,
`Arctic Light Elementary`,
`Barnette Magnet School`,
`Ben Eielson Jr/Sr High School`,
`Boreal Sun Charter School`,
`Chinook Montessori Charter School`,
`Crawford Elementary`,
`Denali Elementary`,
`Effie Kokrine Charter School`,
`Fairbanks B.E.S.T.`,
`Golden Heart Academy`,
`Hunter Elementary`,
`Hutchison High School`,
`Joy Elementary`,
`Ladd Elementary`,
`Lathrop High School`,
`Midnight Sun Elementary School`,
`Nordale Elementary`,
`North Pole Elementary`,
`North Pole High School`,
`North Pole Middle School`,
`Pearl Creek Elementary`,
`Randy Smith Middle School`,
`Ryan Middle School`,
`Salcha Elementary`,
`Star of the North Secondary School`,
`Tanana Middle School`,
`Ticasuk Brown Elementary`,
`Two Rivers School`,
`University Park Elementary`,
`Watershed Charter School`,
`Weller Elementary`,
`West Valley High School`,
`Woodriver Elementary`,
`Galena Interior Learning Academy (GILA)`,
`Interior Distance Education of Alaska (IDEA)`,
`Sidney C. Huntington Elementary`,
`Sidney C. Huntington Jr/Sr High School`,
`Haines Elementary`,
`Haines High School`,
`Haines Home School`,
`Hoonah Elementary`,
`Hoonah Jr/Sr High School`,
`Hydaburg School`,
`Totem Correspondence School`,
`Blackwell School`,
`David Louis Memorial School`,
`Distance Learning/Corresp. Ctr.`,
`Holy Cross School`,
`Innoko River School`,
`McGrath School`,
`Takotna Community School`,
`Top of the Kuskokwim School`,
`Auke Bay Elementary`,
`Dzantik'i Heeni Middle School`,
`Floyd Dryden Middle School`,
`Glacier Valley Elementary`,
`Harborview Elementary`,
`HomeBRIDGE`,
`Johnson Youth Center`,
`Juneau Community Charter School`,
`Juneau-Douglas High School`,
`Mendenhall River Community School`,
`Montessori Borealis Public Alternative School`,
`Riverbend Elementary`,
`Say'ik: Gastineau Community School`,
`Thunder Mountain High School`,
`Yaakoosge Daakahidi Alt. H.S.`,
`Kake Elementary & High School`,
`Chevak School`,
`Aurora Borealis Charter School`,
`Chapman School`,
`Connections`,
`Cooper Landing School`,
`Fireweed Academy`,
`Homer Flex School`,
`Homer High School`,
`Homer Middle School`,
`Hope School`,
`Kachemak Selo School`,
`Kaleidoscope School of Arts & Science`,
`Kalifornsky Beach Elementary`,
`Kenai Alternative High School`,
`Kenai Central High School`,
`Kenai Middle School`,
`Marathon School`,
`McNeil Canyon Elementary`,
`Moose Pass School`,
`Mt. View Elementary`,
`Nanwalek School`,
`Nikiski Middle/Senior High School`,
`Nikiski North Star Elementary`,
`Nikolaevsk School`,
`Ninilchik School`,
`Port Graham School`,
`Razdolna School`,
`Redoubt Elementary`,
`River City Academy`,
`Seward High School`,
`Seward Middle School`,
`Skyview Middle School`,
`Soldotna Elementary`,
`Soldotna High School`,
`Soldotna Montessori Charter School`,
`Sterling Elementary`,
`Susan B English School`,
`Tebughna School`,
`Tustumena Elementary`,
`Voznesenka School`,
`West Homer Elementary`,
`William H. Seward Elementary School`,
`Soldotna Prep School`,
`Fast Track`,
`Fawn Mountain Elementary`,
`Houghtaling Elementary`,
`Ketchikan Charter School`,
`Ketchikan High School`,
`Point Higgins School`,
`Revilla Jr/Sr High School`,
`Schoenbar Middle School`,
`Tongass School of Arts and Sciences Charter School`,
`Klawock City School`,
`Akhiok School`,
`AKTEACH`,
`Chiniak School`,
`East Elementary`,
`Karluk School`,
`Kodiak High School`,
`Kodiak Middle School`,
`Larsen Bay School`,
`Main Elementary`,
`Old Harbor School`,
`Ouzinkie School`,
`Peterson Elementary`,
`Port Lions School`,
`Aniak Jr/Sr High School`,
`Auntie Mary Nicoli Elementary`,
`Crow Village Sam School`,
`George Morgan Sr. H.S.`,
`Gusty Michael School`,
`Jack Egnaty Sr. School`,
`Johnnie John Sr. School`,
`Zackar Levi Elementary`,
`Chignik Bay School`,
`Chignik Lagoon School`,
`Chignik Lake School`,
`Igiugig School`,
`Kokhanok School`,
`Lakeview Home School`,
`Levelock School`,
`Meshik School`,
`Newhalen School`,
`Nondalton School`,
`Perryville School`,
`Pilot Point School`,
`Tanalian School`,
`Akiuk Memorial School`,
`Akula Elitnaurvik School`,
`Anna Tobeluk Memorial School`,
`Arviq School`,
`Ayagina'ar Elitnaurvik`,
`Ayaprun Elitnaurvik`,
`Ayaprun School`,
`Bethel Regional High School`,
`Bethel Youth Facility`,
`Chaputnguak School`,
`Chief Paul Memorial School`,
`Eek School`,
`Gladys Jung Elementary`,
`Joann A. Alexie Memorial School`,
`Ket'acik/Aapalluk Memorial School`,
`Kuinerrarmiut Elitnaurviat`,
`Kuskokwim Learning Academy`,
`Kwigillingok School`,
`Lewis Angapak Memorial School`,
`Negtemiut Elitnaurviat School`,
`Nelson Island Area School`,
`Nuniwarmiut School`,
`Paul T. Albert Memorial School`,
`Qugcuun Memorial School`,
`Rocky Mountain School`,
`William Miller Memorial School`,
`Z. John Williams Memorial School`,
`Alakanuk School`,
`Emmonak School`,
`Hooper Bay School`,
`Kotlik School`,
`Marshall School`,
`Mountain Village School`,
`Nunam Iqua School`,
`Pilot Station School`,
`Russian Mission School`,
`Scammon Bay School`,
`Academy Charter School`,
`American Charter Academy`,
`Beryozova School`,
`Big Lake Elementary`,
`Birchtree Charter School`,
`Burchell High School`,
`Butte Elementary`,
`Colony High School`,
`Colony Middle School`,
`Cottonwood Creek Elementary`,
`Dena_ina Elementary School`,
`Finger Lake Elementary`,
`Fred and Sara Machetanz Elementary School`,
`Fronteras Charter School`,
`Glacier View School`,
`Houston High School`,
`Houston Middle School`,
`Iditarod Elementary`,
`Joe Redington Senior Jr/Sr High School`,
`John Shaw Elementary`,
`Knik Elementary School`,
`Larson Elementary`,
`Mat-Su Career & Tech Ed High School`,
`Mat-Su Central School`,
`Mat-Su Day School`,
`Mat-Su Youth Facility`,
`Meadow Lakes Elementary`,
`Midnight Sun Family Learning Center`,
`Palmer High School`,
`Palmer Middle School`,
`Pioneer Peak Elementary`,
`Sherrod Elementary`,
`Snowshoe Elementary`,
`Susitna Valley High`,
`Sutton Elementary`,
`Talkeetna Elementary`,
`Tanaina Elementary`,
`Teeland Middle School`,
`Trapper Creek Elementary`,
`Twindly Bridge Charter School`,
`Valley Pathways`,
`Wasilla High School`,
`Wasilla Middle School`,
`Willow Elementary`,
`Mt. Edgecumbe High School`,
`CyberLynx Correspondence Program`,
`Nenana City School`,
`Anvil City Science Academy`,
`Extensions Correspondence`,
`Nome Elementary`,
`Nome-Beltz Jr/Sr High`,
`Nome Youth Facility`,
`Alak School`,
`Barrow High School`,
`Eben Hopson Middle School`,
`Fred Ipalook Elementary`,
`Harold Kaveolook School`,
`Kali School`,
`Kiita Learning Community`,
`Meade River School`,
`Nuiqsut Trapper School`,
`Nunamiut School`,
`Tikigaq School`,
`Ambler School`,
`Aqqaluk High/Noorvik Elementary`,
`Buckland School`,
`Davis-Ramoth School`,
`Deering School`,
`June Nelson Elementary`,
`Kiana School`,
`Kobuk School`,
`Kotzebue Middle/High School`,
`McQueen School`,
`Napaaqtugmiut School`,
`NWABSD Home School`,
`Shungnak School`,
`Pelican School`,
`Mitkof Middle School`,
`Petersburg High School`,
`Rae C. Stedman Elementary`,
`PSD Correspondence Program`,
`St Paul School`,
`Saint Mary's School`,
`Blatchley Middle School`,
`Keet Gooshi Heen Elementary`,
`Pacific High School`,
`Sitka High School`,
`Sitka REACH`,
`Skagway School`,
`Barry Craig Stewart Kasaan School`,
`Hollis School`,
`Howard Valentine Coffman Cove School`,
`Hyder School`,
`Naukati School`,
`Thorne Bay School`,
`Whale Pass School`,
`Port Alexander School`,
`Aleknagik School`,
`Chief Ivan Blunka School`,
`Clarks Point School`,
`Koliganek School`,
`Manokotak School`,
`Togiak School`,
`Twin Hills School`,
`William "Sonny" Nelson School`,
`Maudrey J. Sommer School`,
`Eagle's View Elementary School`,
`Unalaska Jr/Sr High School`,
`George H. Gilson Middle School`,
`Hermon Hutchens Elementary`,
`Valdez High School`,
`Valdez Home School`,
`Evergreen Elementary`,
`Stikine Middle School`,
`Wrangell High School`,
`LEAD Correspondence`,
`Yakutat School`,
`Arctic Village School`,
`Circle School`,
`Cruikshank School`,
`Fort Yukon School`,
`John Fredson School`,
`Tsuk Taih School`,
`Allakaket School`,
`Andrew K. Demoski School`,
`Ella B. Vernetti School`,
`Gladys Dart School`,
`Jimmy Huntington School`,
`Kaltag School`,
`Merreline A Kangas School`,
`Minto School`,
`Rampart School`,
`Raven School`,
`Johnny Oldman School`,
`Akiachak School`,
`Akiak School`,
`Tuluksak School`,
]
