const individualScores = {
  "Marathon School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Soldotna Prep School": {"Math": "73.8%", "ELA": "66.3%"},
  "Deering School": {"Math": "80% or more", "Science": "60% or more", "ELA": "80% or more"},
  "Interior Distance Education of Alaska (IDEA)": {"Math": "75.4%", "Science": "28.6%", "ELA": "39.6%"},
  "Koliganek School": {"Math": "71.0%", "Science": "75% or more", "ELA": "90% or more"},
  "Bethel Regional High School": {"Math": "84.1%", "Science": "66.5%", "ELA": "81.9%"},
  "River City Academy": {"Math": "77.8%", "Science": "29.6%", "ELA": "50.0%"},
  "Dillingham Middle/High School": {"Math": "77.9%", "Science": "46.3%", "ELA": "64.5%"},
  "Nenana City School": {"Math": "86.1%", "Science": "69.1%", "ELA": "66.3%"},
  "Juneau Community Charter School": {"Math": "47.8%", "Science": "17.4%", "ELA": "39.4%"},
  "Haines Home School": {"Math": "42.9%", "Science": "*", "ELA": "40% or fewer"},
  "Knik Elementary School": {"Math": "46.2%", "Science": "39.3%", "ELA": "55.0%"},
  "Cantwell School": {"Math": "80% or more", "Science": "40% or fewer", "ELA": "54.6%"},
  "Palmer Middle School": {"Math": "73.3%", "Science": "45.6%", "ELA": "49.2%"},
  "Karluk School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Russian Mission School": {"Math": "95% or more", "Science": "85.2%", "ELA": "95% or more"},
  "Homer Flex School": {"Math": "80% or more", "Science": "60% or more", "ELA": "72.7%"},
  "Trapper Creek Elementary": {"Math": "82.4%", "Science": "*", "ELA": "76.5%"},
  "Alak School": {"Math": "93.3%", "Science": "90% or more", "ELA": "95% or more"},
  "Kake Elementary & High School": {"Math": "86.7%", "Science": "36.8%", "ELA": "65.0%"},
  "North Pole Elementary": {"Math": "57.1%", "Science": "51.2%", "ELA": "62.2%"},
  "Fred and Sara Machetanz Elementary School": {"Math": "42.2%", "Science": "35.2%", "ELA": "40.1%"},
  "Chignik Lake School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Colony High School": {"Math": "76.7%", "Science": "21.9%", "ELA": "57.0%"},
  "West Valley High School": {"Math": "70.3%", "Science": "31.6%", "ELA": "56.7%"},
  "Glacier View School": {"Math": "36.8%", "Science": "40% or fewer", "ELA": "15.8%"},
  "Sterling Elementary": {"Math": "65.1%", "Science": "69.2%", "ELA": "68.2%"},
  "Sidney C. Huntington Elementary": {"Math": "57.1%", "Science": "*", "ELA": "50.0%"},
  "Angoon School": {"Math": "88.6%", "Science": "81.3%", "ELA": "81.8%"},
  "Tsuk Taih School": {"Math": "75% or more", "Science": "*", "ELA": "60% or more"},
  "Seward Middle School": {"Math": "60.2%", "Science": "31.3%", "ELA": "45.5%"},
  "Chevak School": {"Math": "96.9%", "Science": "94.3%", "ELA": "93.9%"},
  "Galena Interior Learning Academy (GILA)": {"Math": "97.1%", "Science": "63.5%", "ELA": "81.4%"},
  "Juneau-Douglas High School": {"Math": "65.7%", "Science": "34.0%", "ELA": "55.4%"},
  "Skagway School": {"Math": "26.8%", "Science": "20% or fewer", "ELA": "10.7%"},
  "Ayagina'ar Elitnaurvik": {"Math": "94.9%", "Science": "89.7%", "ELA": "97.0%"},
  "Cottonwood Creek Elementary": {"Math": "44.1%", "Science": "52.9%", "ELA": "50.2%"},
  "Alternative Learning Systems": {"Math": "93.3%", "Science": "80% or more", "ELA": "75.6%"},
  "Homer Middle School": {"Math": "44.9%", "Science": "15.1%", "ELA": "36.0%"},
  "Slana School": {"Math": "54.6%", "Science": "*", "ELA": "36.4%"},
  "William Miller Memorial School": {"Math": "95% or more", "Science": "80% or more", "ELA": "95% or more"},
  "New Horizons High School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Manokotak School": {"Math": "91.4%", "Science": "90% or more", "ELA": "95% or more"},
  "Lewis Angapak Memorial School": {"Math": "95% or more", "Science": "95% or more", "ELA": "95% or more"},
  "Kotzebue Middle/High School": {"Math": "81.7%", "Science": "75.0%", "ELA": "76.8%"},
  "Kokhanok School": {"Math": "72.7%", "Science": "*", "ELA": "72.7%"},
  "Wasilla High School": {"Math": "83.3%", "Science": "42.6%", "ELA": "73.2%"},
  "Nuiqsut Trapper School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "SE Island Correspondence": {"Math": "*", "Science": "*", "ELA": "*"},
  "Chignik Bay School": {"Math": "75% or more", "Science": "*", "ELA": "75% or more"},
  "Mat-Su Day School": {"Math": "95% or more", "Science": "82.4%", "ELA": "87.2%"},
  "Emmonak School": {"Math": "95% or more", "Science": "93.6%", "ELA": "95.9%"},
  "Barnette Magnet School": {"Math": "48.0%", "Science": "42.2%", "ELA": "47.4%"},
  "Susitna Valley High": {"Math": "67.2%", "Science": "25.6%", "ELA": "44.8%"},
  "Fireweed Academy": {"Math": "45.8%", "Science": "25% or fewer", "ELA": "42.4%"},
  "Stikine Middle School": {"Math": "56.3%", "Science": "46.2%", "ELA": "45.8%"},
  "Peterson Elementary": {"Math": "39.6%", "Science": "50.0%", "ELA": "48.7%"},
  "Ella B. Vernetti School": {"Math": "75% or more", "Science": "*", "ELA": "75% or more"},
  "Gusty Michael School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Mentasta Lake School": {"Math": "80% or more", "Science": "60% or more", "ELA": "80% or more"},
  "Rampart School": {"Math": "60% or more", "Science": "*", "ELA": "57.1%"},
  "Igiugig School": {"Math": "75% or more", "Science": "*", "ELA": "50.0%"},
  "Keet Gooshi Heen Elementary": {"Math": "53.1%", "Science": "31.3%", "ELA": "43.0%"},
  "Chinook Montessori Charter School": {"Math": "51.9%", "Science": "35.1%", "ELA": "43.3%"},
  "Koyuk-Malimiut School": {"Math": "95.0%", "Science": "90% or more", "ELA": "93.3%"},
  "University Park Elementary": {"Math": "49.7%", "Science": "49.3%", "ELA": "53.2%"},
  "Ketchikan Charter School": {"Math": "54.1%", "Science": "43.8%", "ELA": "53.4%"},
  "Glacier Valley Elementary": {"Math": "62.6%", "Science": "61.3%", "ELA": "66.3%"},
  "Andrew K. Demoski School": {"Math": "90% or more", "Science": "*", "ELA": "90% or more"},
  "Chiniak School": {"Math": "61.5%", "Science": "*", "ELA": "46.2%"},
  "William \"Sonny\" Nelson School": {"Math": "75% or more", "Science": "*", "ELA": "75% or more"},
  "Ben Eielson Jr/Sr High School": {"Math": "68.3%", "Science": "37.0%", "ELA": "51.4%"},
  "Hunter Elementary": {"Math": "66.7%", "Science": "58.5%", "ELA": "73.3%"},
  "Crow Village Sam School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Hollis School": {"Math": "63.6%", "Science": "*", "ELA": "54.6%"},
  "Watershed Charter School": {"Math": "22.8%", "Science": "19.1%", "ELA": "30.5%"},
  "Wrangell High School": {"Math": "62.8%", "Science": "18.8%", "ELA": "54.8%"},
  "Wales School": {"Math": "90% or more", "Science": "80% or more", "ELA": "90% or more"},
  "Barrow High School": {"Math": "81.7%", "Science": "51.2%", "ELA": "76.2%"},
  "FOCUS Homeschool": {"Math": "78.6%", "Science": "47.4%", "ELA": "54.1%"},
  "Pioneer Peak Elementary": {"Math": "39.6%", "Science": "48.6%", "ELA": "39.4%"},
  "Nikiski Middle/Senior High School": {"Math": "76.7%", "Science": "52.5%", "ELA": "58.2%"},
  "Akula Elitnaurvik School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "Evergreen Elementary": {"Math": "54.6%", "Science": "50.0%", "ELA": "72.7%"},
  "Gladys Dart School": {"Math": "50.0%", "Science": "60% or more", "ELA": "37.5%"},
  "Birchtree Charter School": {"Math": "64.0%", "Science": "47.7%", "ELA": "45.8%"},
  "Shungnak School": {"Math": "95% or more", "Science": "80% or more", "ELA": "95% or more"},
  "LEAD Correspondence": {"Math": "56.3%", "Science": "*", "ELA": "46.7%"},
  "North Star Elementary": {"Math": "62.8%", "Science": "58.3%", "ELA": "62.8%"},
  "Riverbend Elementary": {"Math": "58.3%", "Science": "62.2%", "ELA": "57.5%"},
  "Akiachak School": {"Math": "96.8%", "Science": "90% or more", "ELA": "95% or more"},
  "Hyder School": {"Math": "75% or more", "Science": "*", "ELA": "55.6%"},
  "Allakaket School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Valdez Home School": {"Math": "77.3%", "Science": "*", "ELA": "40.9%"},
  "Mitkof Middle School": {"Math": "60.7%", "Science": "50.0%", "ELA": "43.3%"},
  "Aurora Borealis Charter School": {"Math": "10.7%", "Science": "15.4%", "ELA": "16.5%"},
  "Arviq School": {"Math": "75% or more", "Science": "*", "ELA": "66.7%"},
  "Kuskokwim Learning Academy": {"Math": "95% or more", "Science": "77.8%", "ELA": "90% or more"},
  "Cordova School District Innovative Learning": {"Math": "*", "Science": "*", "ELA": "*"},
  "Alakanuk School": {"Math": "97.2%", "Science": "93.7%", "ELA": "95.1%"},
  "John Fredson School": {"Math": "90% or more", "Science": "60% or more", "ELA": "90% or more"},
  "Redoubt Elementary": {"Math": "52.0%", "Science": "50.0%", "ELA": "48.8%"},
  "Glennallen Jr/Sr High School": {"Math": "61.0%", "Science": "22.7%", "ELA": "44.6%"},
  "Rae C. Stedman Elementary": {"Math": "52.3%", "Science": "47.6%", "ELA": "46.7%"},
  "Pearl Creek Elementary": {"Math": "36.8%", "Science": "39.7%", "ELA": "40.1%"},
  "Napaaqtugmiut School": {"Math": "97.0%", "Science": "90% or more", "ELA": "95.9%"},
  "Shishmaref School": {"Math": "91.8%", "Science": "80.0%", "ELA": "90.9%"},
  "Mendenhall River Community School": {"Math": "56.9%", "Science": "61.4%", "ELA": "58.8%"},
  "Twin Hills School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Dillingham Correspondence School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Nikolaevsk School": {"Math": "62.5%", "Science": "38.5%", "ELA": "47.5%"},
  "Houston Middle School": {"Math": "88.5%", "Science": "57.3%", "ELA": "66.6%"},
  "Hoonah Jr/Sr High School": {"Math": "88.0%", "Science": "46.2%", "ELA": "72.0%"},
  "Z. John Williams Memorial School": {"Math": "93.2%", "Science": "78.6%", "ELA": "93.2%"},
  "Harold Kaveolook School": {"Math": "87.9%", "Science": "75% or more", "ELA": "84.9%"},
  "Haines Elementary": {"Math": "45.5%", "Science": "26.3%", "ELA": "43.4%"},
  "Moose Pass School": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Alaska REACH Academy": {"Math": "*", "Science": "*", "ELA": "*"},
  "Saint Mary's School": {"Math": "79.8%", "Science": "73.8%", "ELA": "86.0%"},
  "Innoko River School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Joann A. Alexie Memorial School": {"Math": "95% or more", "Science": "85.0%", "ELA": "95% or more"},
  "Richard Johnson Elementary": {"Math": "74.0%", "Science": "74.1%", "ELA": "72.7%"},
  "False Pass School": {"Math": "57.1%", "Science": "50.0%", "ELA": "57.1%"},
  "Scammon Bay School": {"Math": "97.4%", "Science": "93.0%", "ELA": "95.7%"},
  "Chaputnguak School": {"Math": "95% or more", "Science": "88.5%", "ELA": "95% or more"},
  "PACE Correspondence": {"Math": "65.4%", "Science": "41.3%", "ELA": "44.0%"},
  "St Paul School": {"Math": "90% or more", "Science": "66.7%", "ELA": "74.3%"},
  "Academy Charter School": {"Math": "50.6%", "Science": "40.0%", "ELA": "40.6%"},
  "Razdolna School": {"Math": "86.9%", "Science": "78.6%", "ELA": "82.0%"},
  "Kwigillingok School": {"Math": "95% or more", "Science": "90.3%", "ELA": "95% or more"},
  "William H. Seward Elementary School": {"Math": "53.0%", "Science": "41.7%", "ELA": "53.0%"},
  "Buckland School": {"Math": "94.7%", "Science": "83.7%", "ELA": "92.6%"},
  "Rocky Mountain School": {"Math": "87.9%", "Science": "80% or more", "ELA": "90% or more"},
  "Denali PEAK": {"Math": "67.1%", "Science": "48.1%", "ELA": "49.9%"},
  "Qugcuun Memorial School": {"Math": "62.5%", "Science": "*", "ELA": "75% or more"},
  "Kobuk School": {"Math": "90% or more", "Science": "80% or more", "ELA": "90% or more"},
  "Gambell School": {"Math": "95% or more", "Science": "90% or more", "ELA": "96.5%"},
  "Davis-Ramoth School": {"Math": "95% or more", "Science": "95% or more", "ELA": "95% or more"},
  "Adak School": {"Math": "80% or more", "Science": "40% or fewer", "ELA": "40.0%"},
  "Kaleidoscope School of Arts & Science": {"Math": "55.7%", "Science": "37.2%", "ELA": "60.5%"},
  "Thorne Bay School": {"Math": "88.4%", "Science": "64.3%", "ELA": "69.8%"},
  "Meadow Lakes Elementary": {"Math": "61.0%", "Science": "55.7%", "ELA": "65.3%"},
  "Hope School": {"Math": "60.0%", "Science": "*", "ELA": "40.0%"},
  "Kenny Lake School": {"Math": "56.1%", "Science": "22.2%", "ELA": "41.5%"},
  "Minto School": {"Math": "90% or more", "Science": "50.0%", "ELA": "88.2%"},
  "Mt. View Elementary": {"Math": "55.9%", "Science": "50.7%", "ELA": "55.9%"},
  "Soldotna Montessori Charter School": {"Math": "57.8%", "Science": "39.1%", "ELA": "37.1%"},
  "Meade River School": {"Math": "90% or more", "Science": "80% or more", "ELA": "90% or more"},
  "Bristol Bay Correspondence": {"Math": "*", "Science": "*", "ELA": "*"},
  "Tatitlek Community School": {"Math": "75% or more", "Science": "50.0%", "ELA": "55.6%"},
  "Tustumena Elementary": {"Math": "57.9%", "Science": "36.7%", "ELA": "48.4%"},
  "Midnight Sun Elementary School": {"Math": "49.0%", "Science": "48.8%", "ELA": "62.1%"},
  "Tok School": {"Math": "79.1%", "Science": "58.6%", "ELA": "75.5%"},
  "Nome-Beltz Jr/Sr High": {"Math": "84.1%", "Science": "70.9%", "ELA": "75.9%"},
  "Burchell High School": {"Math": "95% or more", "Science": "60.0%", "ELA": "81.4%"},
  "Chief Ivan Blunka School": {"Math": "96.1%", "Science": "90% or more", "ELA": "95% or more"},
  "Petersburg High School": {"Math": "71.0%", "Science": "41.9%", "ELA": "46.4%"},
  "Tetlin School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Holy Cross School": {"Math": "81.8%", "Science": "57.1%", "ELA": "77.3%"},
  "Aqqaluk High/Noorvik Elementary": {"Math": "95% or more", "Science": "87.5%", "ELA": "92.5%"},
  "Akiuk Memorial School": {"Math": "95% or more", "Science": "80% or more", "ELA": "95% or more"},
  "Finger Lake Elementary": {"Math": "43.3%", "Science": "42.9%", "ELA": "43.3%"},
  "John Shaw Elementary": {"Math": "44.0%", "Science": "29.6%", "ELA": "48.5%"},
  "Colony Middle School": {"Math": "66.3%", "Science": "49.5%", "ELA": "44.9%"},
  "Sitka REACH": {"Math": "61.5%", "Science": "40% or fewer", "ELA": "53.9%"},
  "David Louis Memorial School": {"Math": "90% or more", "Science": "80% or more", "ELA": "90% or more"},
  "Hutchison High School": {"Math": "70.5%", "Science": "15.9%", "ELA": "55.6%"},
  "East Elementary": {"Math": "57.3%", "Science": "71.4%", "ELA": "58.7%"},
  "Nunam Iqua School": {"Math": "90% or more", "Science": "80% or more", "ELA": "90% or more"},
  "Ninilchik School": {"Math": "66.3%", "Science": "33.3%", "ELA": "53.8%"},
  "George H. Gilson Middle School": {"Math": "65.0%", "Science": "61.9%", "ELA": "48.8%"},
  "Danger Bay School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Gerstle River School": {"Math": "80% or more", "Science": "80% or more", "ELA": "81.3%"},
  "Auke Bay Elementary": {"Math": "47.4%", "Science": "31.9%", "ELA": "37.1%"},
  "Woodriver Elementary": {"Math": "45.0%", "Science": "41.3%", "ELA": "53.0%"},
  "Kenai Middle School": {"Math": "63.0%", "Science": "45.0%", "ELA": "49.5%"},
  "Hoonah Elementary": {"Math": "60.6%", "Science": "62.5%", "ELA": "69.7%"},
  "Walter Northway School": {"Math": "90% or more", "Science": "75% or more", "ELA": "90% or more"},
  "Eben Hopson Middle School": {"Math": "87.3%", "Science": "84.4%", "ELA": "78.8%"},
  "Craig High School": {"Math": "86.5%", "Science": "31.3%", "ELA": "67.6%"},
  "Snowshoe Elementary": {"Math": "58.6%", "Science": "46.2%", "ELA": "50.5%"},
  "Beryozova School": {"Math": "66.7%", "Science": "57.1%", "ELA": "44.4%"},
  "Ket'acik/Aapalluk Memorial School": {"Math": "95% or more", "Science": "94.7%", "ELA": "97.4%"},
  "Joe Redington Senior Jr/Sr High School": {"Math": "84.6%", "Science": "55.4%", "ELA": "65.4%"},
  "Fred Ipalook Elementary": {"Math": "74.1%", "Science": "87.1%", "ELA": "87.1%"},
  "Tuluksak School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "Jack Egnaty Sr. School": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Gustavus School": {"Math": "57.8%", "Science": "30.8%", "ELA": "26.7%"},
  "Tri-Valley School": {"Math": "58.1%", "Science": "25.0%", "ELA": "38.1%"},
  "Martin L. Olson School": {"Math": "90% or more", "Science": "75% or more", "ELA": "90% or more"},
  "Old Harbor School": {"Math": "71.4%", "Science": "60% or more", "ELA": "71.4%"},
  "Craig Elementary": {"Math": "74.4%", "Science": "33.3%", "ELA": "60.3%"},
  "Wasilla Middle School": {"Math": "76.7%", "Science": "43.9%", "ELA": "59.6%"},
  "Ayaprun School": {"Math": "95% or more", "Science": "90.6%", "ELA": "95% or more"},
  "Fort Yukon School": {"Math": "85.7%", "Science": "90% or more", "ELA": "94.7%"},
  "Akutan School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Mt. Eccles Elementary": {"Math": "51.8%", "Science": "31.6%", "ELA": "51.8%"},
  "Nanwalek School": {"Math": "95% or more", "Science": "80% or more", "ELA": "90.0%"},
  "Mat-Su Youth Facility": {"Math": "*", "Science": "*", "ELA": "*"},
  "Chignik Lagoon School": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Kenai Central High School": {"Math": "80.4%", "Science": "45.4%", "ELA": "63.3%"},
  "Anderson School": {"Math": "76.5%", "Science": "50.0%", "ELA": "58.8%"},
  "Fawn Mountain Elementary": {"Math": "67.2%", "Science": "64.9%", "ELA": "58.3%"},
  "Iditarod Elementary": {"Math": "62.5%", "Science": "71.2%", "ELA": "56.5%"},
  "Maudrey J. Sommer School": {"Math": "86.4%", "Science": "60% or more", "ELA": "86.4%"},
  "Raven School": {"Math": "77.5%", "Science": "48.5%", "ELA": "55.5%"},
  "Tebughna School": {"Math": "84.2%", "Science": "60% or more", "ELA": "90% or more"},
  "Howard Valentine Coffman Cove School": {"Math": "70.0%", "Science": "*", "ELA": "70.0%"},
  "Hogarth Kingeekuk Sr. Memorial School": {"Math": "95% or more", "Science": "94.4%", "ELA": "95% or more"},
  "Homer High School": {"Math": "57.5%", "Science": "23.9%", "ELA": "41.4%"},
  "Levelock School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Larson Elementary": {"Math": "48.9%", "Science": "54.8%", "ELA": "43.1%"},
  "Yakov E. Netsvetov School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Willow Elementary": {"Math": "50.0%", "Science": "63.2%", "ELA": "48.3%"},
  "Crawford Elementary": {"Math": "44.4%", "Science": "53.9%", "ELA": "42.1%"},
  "Sidney C. Huntington Jr/Sr High School": {"Math": "76.0%", "Science": "63.6%", "ELA": "56.0%"},
  "Anvil City Science Academy": {"Math": "39.7%", "Science": "28.6%", "ELA": "36.2%"},
  "Tanana Middle School": {"Math": "71.2%", "Science": "49.5%", "ELA": "55.3%"},
  "Unalaska Jr/Sr High School": {"Math": "52.2%", "Science": "28.3%", "ELA": "39.1%"},
  "Cordova Jr/Sr High School": {"Math": "69.3%", "Science": "30.2%", "ELA": "47.5%"},
  "Unalakleet School": {"Math": "64.0%", "Science": "78.4%", "ELA": "77.0%"},
  "Skyview Middle School": {"Math": "75.3%", "Science": "44.3%", "ELA": "56.1%"},
  "St George School": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Gladys Jung Elementary": {"Math": "85.2%", "Science": "82.9%", "ELA": "83.1%"},
  "Haines High School": {"Math": "66.7%", "Science": "30.8%", "ELA": "52.8%"},
  "Pilot Station School": {"Math": "95% or more", "Science": "90% or more", "ELA": "97.3%"},
  "Naknek Elementary": {"Math": "54.2%", "Science": "60% or more", "ELA": "70.8%"},
  "Dzantik'i Heeni Middle School": {"Math": "66.4%", "Science": "54.7%", "ELA": "54.9%"},
  "James C. Isabell School": {"Math": "71.8%", "Science": "82.4%", "ELA": "90% or more"},
  "Aniguiin School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "Harborview Elementary": {"Math": "53.7%", "Science": "73.9%", "ELA": "65.5%"},
  "Distance Learning/Corresp. Ctr.": {"Math": "*", "Science": "*", "ELA": "*"},
  "Takotna Community School": {"Math": "66.7%", "Science": "40% or fewer", "ELA": "66.7%"},
  "AKTEACH": {"Math": "71.1%", "Science": "52.9%", "ELA": "56.5%"},
  "Pacific High School": {"Math": "80% or more", "Science": "40% or fewer", "ELA": "69.2%"},
  "Shaktoolik School": {"Math": "93.5%", "Science": "82.4%", "ELA": "95% or more"},
  "North Pole Middle School": {"Math": "67.3%", "Science": "45.9%", "ELA": "65.5%"},
  "Dot Lake School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Kachemak Selo School": {"Math": "88.9%", "Science": "78.6%", "ELA": "77.8%"},
  "Chenega Bay School": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Fairbanks B.E.S.T.": {"Math": "62.8%", "Science": "34.3%", "ELA": "39.8%"},
  "Star of the North Secondary School": {"Math": "91.2%", "Science": "62.5%", "ELA": "80.7%"},
  "Revilla Jr/Sr High School": {"Math": "88.6%", "Science": "68.4%", "ELA": "65.9%"},
  "Butte Elementary": {"Math": "58.5%", "Science": "61.4%", "ELA": "57.4%"},
  "Point Higgins School": {"Math": "52.1%", "Science": "55.6%", "ELA": "52.1%"},
  "Nordale Elementary": {"Math": "58.0%", "Science": "67.9%", "ELA": "67.9%"},
  "Sitka High School": {"Math": "77.7%", "Science": "31.7%", "ELA": "55.6%"},
  "Anthony A. Andrews School": {"Math": "94.7%", "Science": "95% or more", "ELA": "94.7%"},
  "Delta/Greely Homeschool": {"Math": "62.0%", "Science": "36.8%", "ELA": "46.0%"},
  "Whale Pass School": {"Math": "60.0%", "Science": "*", "ELA": "40.0%"},
  "Arctic Village School": {"Math": "90% or more", "Science": "75% or more", "ELA": "90% or more"},
  "June Nelson Elementary": {"Math": "80.4%", "Science": "86.4%", "ELA": "79.8%"},
  "West Homer Elementary": {"Math": "35.7%", "Science": "28.9%", "ELA": "40.6%"},
  "Tongass School of Arts and Sciences Charter School": {"Math": "46.8%", "Science": "72.7%", "ELA": "59.7%"},
  "Mat-Su Central School": {"Math": "80.6%", "Science": "41.0%", "ELA": "47.2%"},
  "Bristol Bay Middle/High School": {"Math": "62.5%", "Science": "33.3%", "ELA": "45.0%"},
  "Blackwell School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Paul T. Albert Memorial School": {"Math": "93.9%", "Science": "76.2%", "ELA": "95.4%"},
  "Denaina Elementary School": {"Math": "63.9%", "Science": "54.0%", "ELA": "53.3%"},
  "Merreline A Kangas School": {"Math": "80.0%", "Science": "60% or more", "ELA": "90% or more"},
  "Tukurngailnguq School": {"Math": "95% or more", "Science": "91.4%", "ELA": "95% or more"},
  "Marshall School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "Floyd Dryden Middle School": {"Math": "68.3%", "Science": "55.5%", "ELA": "56.6%"},
  "McNeil Canyon Elementary": {"Math": "37.7%", "Science": "16.7%", "ELA": "33.8%"},
  "Sherrod Elementary": {"Math": "46.5%", "Science": "53.2%", "ELA": "48.2%"},
  "King Cove School": {"Math": "80.4%", "Science": "58.3%", "ELA": "55.4%"},
  "Randy Smith Middle School": {"Math": "60.3%", "Science": "37.7%", "ELA": "52.6%"},
  "Arctic Light Elementary": {"Math": "70.7%", "Science": "70.4%", "ELA": "63.1%"},
  "Lakeview Home School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Zackar Levi Elementary": {"Math": "82.9%", "Science": "80% or more", "ELA": "90% or more"},
  "Thunder Mountain High School": {"Math": "70.1%", "Science": "40.8%", "ELA": "60.4%"},
  "Kiita Learning Community": {"Math": "*", "Science": "*", "ELA": "*"},
  "Yakutat School": {"Math": "84.6%", "Science": "44.4%", "ELA": "71.8%"},
  "Fronteras Charter School": {"Math": "56.8%", "Science": "33.3%", "ELA": "37.8%"},
  "Bethel Youth Facility": {"Math": "*", "Science": "*", "ELA": "*"},
  "Ouzinkie School": {"Math": "80% or more", "Science": "60% or more", "ELA": "80% or more"},
  "Fast Track": {"Math": "76.7%", "Science": "33.3%", "ELA": "53.3%"},
  "Negtemiut Elitnaurviat School": {"Math": "95% or more", "Science": "80% or more", "ELA": "90% or more"},
  "Ambler School": {"Math": "95% or more", "Science": "75% or more", "ELA": "95% or more"},
  "Johnnie John Sr. School": {"Math": "80% or more", "Science": "60% or more", "ELA": "80% or more"},
  "Soldotna High School": {"Math": "81.1%", "Science": "40.9%", "ELA": "63.5%"},
  "Connections": {"Math": "69.0%", "Science": "50.0%", "ELA": "50.9%"},
  "Weller Elementary": {"Math": "50.7%", "Science": "53.0%", "ELA": "52.9%"},
  "Yukon Flats Distance Education Program": {"Math": "*", "Science": "*", "ELA": "*"},
  "Effie Kokrine Charter School": {"Math": "88.5%", "Science": "70.0%", "ELA": "77.1%"},
  "Delta Junction Elementary": {"Math": "44.9%", "Science": "47.4%", "ELA": "55.1%"},
  "Teeland Middle School": {"Math": "67.4%", "Science": "42.9%", "ELA": "45.2%"},
  "Kodiak High School": {"Math": "91.8%", "Science": "50.0%", "ELA": "72.1%"},
  "Chatham Correspondence": {"Math": "*", "Science": "*", "ELA": "*"},
  "Valley Pathways": {"Math": "72.6%", "Science": "32.7%", "ELA": "60.0%"},
  "Anne Wien Elementary": {"Math": "70.1%", "Science": "75.0%", "ELA": "75.5%"},
  "Kuinerrarmiut Elitnaurviat": {"Math": "98.0%", "Science": "93.9%", "ELA": "97.4%"},
  "Eagle Community School": {"Math": "80% or more", "Science": "42.9%", "ELA": "80% or more"},
  "Mat-Su Career & Tech Ed High School": {"Math": "43.5%", "Science": "6.9%", "ELA": "30.6%"},
  "Diomede School": {"Math": "80% or more", "Science": "80% or more", "ELA": "80% or more"},
  "Yaakoosge Daakahidi Alt. H.S.": {"Math": "90% or more", "Science": "66.7%", "ELA": "90% or more"},
  "Pelican School": {"Math": "75% or more", "Science": "60% or more", "ELA": "50.0%"},
  "Blatchley Middle School": {"Math": "66.0%", "Science": "35.3%", "ELA": "42.0%"},
  "Klawock City School": {"Math": "73.9%", "Science": "75.0%", "ELA": "85.5%"},
  "McGrath School": {"Math": "90% or more", "Science": "50.0%", "ELA": "67.9%"},
  "Tanacross School": {"Math": "75% or more", "Science": "*", "ELA": "75% or more"},
  "Nuniwarmiut School": {"Math": "90% or more", "Science": "60% or more", "ELA": "90% or more"},
  "Nome Elementary": {"Math": "83.4%", "Science": "90.2%", "ELA": "88.4%"},
  "Cruikshank School": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Eek School": {"Math": "95% or more", "Science": "87.0%", "ELA": "95% or more"},
  "American Charter Academy": {"Math": "50.0%", "Science": "37.1%", "ELA": "35.7%"},
  "Ketchikan High School": {"Math": "80.1%", "Science": "37.2%", "ELA": "58.9%"},
  "Upstream Learning Correspondence": {"Math": "65.9%", "Science": "58.8%", "ELA": "47.7%"},
  "Chapman School": {"Math": "53.0%", "Science": "36.8%", "ELA": "43.9%"},
  "Meshik School": {"Math": "75.0%", "Science": "*", "ELA": "80% or more"},
  "Craig Middle School": {"Math": "84.1%", "Science": "30.4%", "ELA": "43.6%"},
  "Twindly Bridge Charter School": {"Math": "76.0%", "Science": "51.3%", "ELA": "45.1%"},
  "CyberLynx Correspondence Program": {"Math": "84.3%", "Science": "41.2%", "ELA": "52.1%"},
  "Port Alexander School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Nikiski North Star Elementary": {"Math": "59.7%", "Science": "62.5%", "ELA": "62.0%"},
  "Brevig Mission School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "Port Lions School": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Main Elementary": {"Math": "74.0%", "Science": "73.9%", "ELA": "68.6%"},
  "Perryville School": {"Math": "80% or more", "Science": "60% or more", "ELA": "78.6%"},
  "Sand Point School": {"Math": "68.9%", "Science": "54.6%", "ELA": "59.0%"},
  "Joy Elementary": {"Math": "62.6%", "Science": "64.7%", "ELA": "68.5%"},
  "Larsen Bay School": {"Math": "80% or more", "Science": "40% or fewer", "ELA": "71.4%"},
  "Dillingham Elementary": {"Math": "63.6%", "Science": "68.8%", "ELA": "61.3%"},
  "NWABSD Home School": {"Math": "80% or more", "Science": "60% or more", "ELA": "84.2%"},
  "Nome Youth Facility": {"Math": "*", "Science": "*", "ELA": "*"},
  "Two Rivers School": {"Math": "70.6%", "Science": "60.0%", "ELA": "76.5%"},
  "Aleknagik School": {"Math": "71.4%", "Science": "60% or more", "ELA": "81.0%"},
  "Salcha Elementary": {"Math": "45.7%", "Science": "80% or more", "ELA": "54.4%"},
  "Metlakatla High School": {"Math": "93.2%", "Science": "59.1%", "ELA": "79.6%"},
  "Voznesenka School": {"Math": "92.1%", "Science": "61.9%", "ELA": "73.0%"},
  "Golden Heart Academy": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Kodiak Middle School": {"Math": "68.1%", "Science": "48.9%", "ELA": "59.6%"},
  "Nelson Island Area School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "Sutton Elementary": {"Math": "59.1%", "Science": "*", "ELA": "54.6%"},
  "Kaltag School": {"Math": "80% or more", "Science": "*", "ELA": "80% or more"},
  "Hooper Bay School": {"Math": "97.4%", "Science": "95.9%", "ELA": "98.9%"},
  "Aniak Jr/Sr High School": {"Math": "90% or more", "Science": "30.0%", "ELA": "70.0%"},
  "Totem Correspondence School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Charles R. Leask Sr. Middle School": {"Math": "80.4%", "Science": "75.0%", "ELA": "67.9%"},
  "Midnight Sun Family Learning Center": {"Math": "43.8%", "Science": "57.7%", "ELA": "39.7%"},
  "Susan B English School": {"Math": "41.2%", "Science": "*", "ELA": "23.5%"},
  "Nondalton School": {"Math": "80% or more", "Science": "60% or more", "ELA": "83.3%"},
  "Houston High School": {"Math": "92.4%", "Science": "51.4%", "ELA": "83.0%"},
  "Port Graham School": {"Math": "80.0%", "Science": "57.1%", "ELA": "65.0%"},
  "Barry Craig Stewart Kasaan School": {"Math": "57.1%", "Science": "*", "ELA": "60% or more"},
  "White Mountain School": {"Math": "86.7%", "Science": "80% or more", "ELA": "90% or more"},
  "Houghtaling Elementary": {"Math": "54.5%", "Science": "66.7%", "ELA": "53.4%"},
  "Talkeetna Elementary": {"Math": "74.1%", "Science": "50.0%", "ELA": "63.2%"},
  "Tikigaq School": {"Math": "97.8%", "Science": "87.2%", "ELA": "93.3%"},
  "Togiak School": {"Math": "95% or more", "Science": "95% or more", "ELA": "97.5%"},
  "Denali Elementary": {"Math": "64.5%", "Science": "81.1%", "ELA": "63.3%"},
  "McQueen School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "North Pole High School": {"Math": "89.1%", "Science": "49.0%", "ELA": "74.6%"},
  "George Morgan Sr. H.S.": {"Math": "95% or more", "Science": "80% or more", "ELA": "95% or more"},
  "Valdez High School": {"Math": "77.9%", "Science": "23.9%", "ELA": "62.1%"},
  "Tanaina Elementary": {"Math": "53.2%", "Science": "58.9%", "ELA": "62.6%"},
  "Akiak School": {"Math": "95% or more", "Science": "90% or more", "ELA": "94.1%"},
  "HomeBRIDGE": {"Math": "67.9%", "Science": "38.5%", "ELA": "53.6%"},
  "Mountain Village School": {"Math": "95% or more", "Science": "87.8%", "ELA": "95% or more"},
  "Circle School": {"Math": "80% or more", "Science": "60% or more", "ELA": "80% or more"},
  "Palmer High School": {"Math": "78.0%", "Science": "28.1%", "ELA": "60.0%"},
  "Gastineau Elementary": {"Math": "58.6%", "Science": "51.4%", "ELA": "56.3%"},
  "Kotlik School": {"Math": "95% or more", "Science": "90% or more", "ELA": "97.3%"},
  "Jimmy Huntington School": {"Math": "90.0%", "Science": "80% or more", "ELA": "87.5%"},
  "Newhalen School": {"Math": "81.5%", "Science": "70.0%", "ELA": "81.5%"},
  "Johnson Youth Center": {"Math": "60% or more", "Science": "*", "ELA": "60% or more"},
  "Akhiok School": {"Math": "80% or more", "Science": "60% or more", "ELA": "80% or more"},
  "Klukwan School": {"Math": "80% or more", "Science": "*", "ELA": "50.0%"},
  "Kiana School": {"Math": "95% or more", "Science": "90% or more", "ELA": "90.3%"},
  "Mt. Edgecumbe High School": {"Math": "84.3%", "Science": "40.5%", "ELA": "74.8%"},
  "Ayaprun Elitnaurvik": {"Math": "76.9%", "Science": "90% or more", "ELA": "84.6%"},
  "Cooper Landing School": {"Math": "37.5%", "Science": "*", "ELA": "37.5%"},
  "Tanalian School": {"Math": "47.4%", "Science": "20% or fewer", "ELA": "43.6%"},
  "Montessori Borealis Public Alternative School": {"Math": "57.3%", "Science": "34.2%", "ELA": "48.7%"},
  "Lathrop High School": {"Math": "79.7%", "Science": "41.5%", "ELA": "68.2%"},
  "Kalifornsky Beach Elementary": {"Math": "52.6%", "Science": "22.9%", "ELA": "48.3%"},
  "Chief Paul Memorial School": {"Math": "96.9%", "Science": "82.7%", "ELA": "96.9%"},
  "Ticasuk Brown Elementary": {"Math": "69.6%", "Science": "58.1%", "ELA": "67.9%"},
  "Eagle's View Elementary School": {"Math": "55.3%", "Science": "69.2%", "ELA": "57.3%"},
  "Anna Tobeluk Memorial School": {"Math": "95% or more", "Science": "90% or more", "ELA": "95% or more"},
  "Hydaburg School": {"Math": "90.5%", "Science": "80% or more", "ELA": "87.8%"},
  "Johnny Oldman School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Top of the Kuskokwim School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Schoenbar Middle School": {"Math": "70.1%", "Science": "48.0%", "ELA": "56.7%"},
  "Kenai Alternative High School": {"Math": "*", "Science": "*", "ELA": "*"},
  "Auntie Mary Nicoli Elementary": {"Math": "82.5%", "Science": "80% or more", "ELA": "82.5%"},
  "Kali School": {"Math": "95% or more", "Science": "86.4%", "ELA": "90.0%"},
  "Ladd Elementary": {"Math": "52.6%", "Science": "57.8%", "ELA": "56.3%"},
  "Hermon Hutchens Elementary": {"Math": "48.5%", "Science": "35.6%", "ELA": "43.1%"},
  "Big Lake Elementary": {"Math": "55.3%", "Science": "51.0%", "ELA": "59.0%"},
  "Seward High School": {"Math": "79.1%", "Science": "45.2%", "ELA": "59.3%"},
  "Naukati School": {"Math": "72.7%", "Science": "*", "ELA": "63.6%"},
  "Soldotna Elementary": {"Math": "69.7%", "Science": "60.6%", "ELA": "61.5%"},
  "Delta Junction High School": {"Math": "58.9%", "Science": "31.9%", "ELA": "55.2%"},
  "Extensions Correspondence": {"Math": "80% or more", "Science": "*", "ELA": "40.0%"},
  "Whittier Community School": {"Math": "66.7%", "Science": "62.5%", "ELA": "44.4%"},
  "Pilot Point School": {"Math": "75% or more", "Science": "*", "ELA": "75% or more"},
  "Nunamiut School": {"Math": "93.2%", "Science": "80% or more", "ELA": "88.6%"},
  "Ryan Middle School": {"Math": "69.2%", "Science": "55.1%", "ELA": "67.7%"},
  "Glennallen Elementary": {"Math": "65.1%", "Science": "63.2%", "ELA": "59.0%"}
};

export default individualScores;
